version: 2

project_name: mailbus

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    main: ./cmd/mailbus

archives:
  - format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - AGENT_INSTALLATION.md

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - 'README'
      - 'LICENSE'

release:
  draft: false
  prerelease: auto
  mode: replace
